Explicit error for missing enum definition
PostgresRunner threw this error, if a user forgot to include the enum constants in the @Column annotation:

```
TypeError: Cannot read property 'map' of undefined
    at PostgresQueryRunner.createEnumTypeSql
```

This throws a more meaningful error and includes the column / table.